### ISSUE TITLE
gitignore修改意见

### ISSUE THREAD

**Issue by Aprilerr** [ScholarNow/summary_generation#11]
想要在gitignore中添加忽略携带local字段的文件夹与文件，方便本地调试
需求：忽略下面方框框出的部分
![image](https://user-images.githubusercontent.com/45314441/231085398-00dad7e3-d20e-4c55-a130-5e2c682f937e.png)

**Comment by ScottWong98** [comment]
本地调试的话，可以考虑其他两种方式：
- checkout 到一个新的分支
- 在原分支上添加代码进行调试，调试结束后，使用 `git reset --hard HEAD` 去掉修改

当然这种方式也可以，不过我觉得用 `main.debug.py` 可能会更好些，我这边加上这个
