### ISSUE TITLE
存在根据 paper title 搜不到结果的情况

### ISSUE THREAD

**Issue by ScottWong98** [ScholarNow/summary_generation#5]
存在根据 PaperParser 提取到的 Title 在 PaperCrawler 中搜不到结果的情况，需要在 PaperCrawler 中进行处理

出错代码在: 
https://github.com/ScholarNow/summary_generation/blob/8f25664514da7a6417e4d31702047d4bcccf04ad/src/paper_crawler.py#L55-L57

尽管 PaperCrawler 搜不到结果，也应该有相应的提示信息返回给前端页面，不应该在前端页面出现报错

**Comment by Aprilerr** [comment]
我看一下gradio这边怎么返回错误信息，到时候更新到这里

**Comment by Aprilerr** [comment]
我想在外层包一个try exception来获取程序中的错误，并且打印到前端Error中，目前我正在做这个
